name: Upload new Package
description: Upload an new package config!

- type: input
  attributes:
    label: Name
    description: What is the name of your package?
    placeholder: Sqlite
    value: name
  validations:
    required: true

- type: input
  attributes:
    label: Description
    description: What is the description of your package?
    placeholder: Sqlite
    value: description
  validations:
    required: false

- type: input
  attributes:
    label: Repository URL
    description: What is the repository of your package?
    placeholder: github.com/username/package
    value: repository
  validations:
    required: true

- type: input
  attributes:
    label: Website
    description: What is the description of your package?
    placeholder: Sqlite
    value: website
  validations:
    required: false

- type: input
  attributes:
    label: Version
    description: What is the version of your package?
    placeholder: v1.0
    value: version
  validations:
    required: true


- type: markdown
  attributes:
    value: "Thanks for uploading an new package!"
