name: Push on issue creation

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create file
        run: echo "Issue number is ${{ github.event.issue.number }}" > "${{ github.event.issue.bidy }}.txt"
      
      - name: Commit files and close issue
        run: |
          git pull --quiet --force
          git config --global user.email "packageuploader+35432636@bot-noreply.github.com"
          git config --global user.name "[BOT] Package Uploader"
          git add .
          git commit -m "Uploaded Package '#${{ github.event.issue.title }}' based on  #${{ github.event.issue }}"
          git push --quiet
          echo "::set-output name=issue_number::${{ github.event.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close issue
        uses: peter-evans/close-issue@v1.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: 'Closing this issue because it has been approved.'
         

