name: Push on issue creation

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create file
        run: echo "Hello World" > hello.txt

      - name: Commit files and close issue
        run: |
          git pull -f
          git config --global user.email "packageuploader+35432636@bot-noreply.github.com"
          git config --global user.name "[BOT] Package Uploader"
          git add .
          git commit -m "Add hello.txt for issue #${{ github.event.issue.number }} created on $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f
          echo "::set-output name=issue_number::${{ github.event.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close issue
        uses: peter-evans/close-issue@v1.0.0
        with:
          issue-number: ${{ steps.build.outputs.issue_number }}
          comment: 'Closing this issue because it has been approved.'
         

